name: Release
on:
  push:
    tags:
      - v*
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Docker Hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: make docker
